In [174]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.utils import shuffle 
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

Importing the data from the csv file into panda dataframe

In [175]:
data=pd.read_csv("/Users/oshanoshu/firstMachineLearning/cleaned.csv")
data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
5                    0.41             0.50               2   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
8                    0.89             1.00               5   
9                    0.42             0.53               2   
10                   0.45             0.54               2   
11                   0.11             0.81               6   
12                   0.84             0.92               4   
13                   0.41             0.55               2   
14                   0.36             0.56               2   
15                   0.38             0.54               2   
16                   0.45             0.47               2   
17                   0.78             0.99               4   
18                   0.45             0.51               2   
19                   0.76             0.89               5   
20                   0.11             0.83               6   
21                   0.38             0.55               2   
22                   0.09             0.95               6   
23                   0.46             0.57               2   
24                   0.40             0.53               2   
25                   0.89             0.92               5   
26                   0.82             0.87               4   
27                   0.40             0.49               2   
28                   0.41             0.46               2   
29                   0.38             0.50               2   
...                   ...              ...             ...   
12229                0.94             0.82               4   
12230                0.50             0.64               2   
12231                0.82             0.76               3   
12232                0.85             0.64               5   
12233                0.82             0.67               3   
12234                0.90             0.89               4   
12235                0.40             0.54               2   
12236                0.84             0.88               4   
12237                0.11             0.91               6   
12238                0.83             1.00               5   
12239                0.41             0.46               2   
12240                0.37             0.51               2   
12241                0.42             0.56               2   
12242                0.45             0.53               2   
12243                0.09             0.97               7   
12244                0.80             0.53               3   
12245                0.11             0.87               5   
12246                0.19             1.00               4   
12247                0.44             0.52               2   
12248                0.76             0.98               5   
12249                0.81             0.92               5   
12250                0.42             0.57               2   
12251                0.37             0.49               2   
12252                0.83             0.81               5   
12253                0.43             0.51               2   
12254                0.40             0.47               2   
12255                0.43             0.46               2   
12256                0.89             0.88               5   
12257                0.76             0.83               6   
12258                0.37             0.48               2   

       average_montly_hours  time_spend_company  work_accident  left  \
0                157.000000            3.000000              0     1   
1                2

Converting all the salary values to numeric

In [176]:
def changeToInt(x):
    if x=='low':
        return 1
    elif x=='medium':
        return 2
    else:
        return 3
data.salary=data['salary'].apply(changeToInt)

Converting all the department values to numeric value

In [177]:
data.department.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [187]:
data.department.replace(('sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'),(1,2,3,4,5,6,7,8,9,10),inplace=True)

Name of columns

In [188]:
data.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'work_accident', 'left',
       'promotion_last_5years', 'department', 'salary'],
      dtype='object')

Separating features and target from the data

In [189]:
x_data=data[['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'work_accident',
       'promotion_last_5years', 'department', 'salary']]

In [190]:
y_data=data['left']

Function on k-Fold Validation and Classifier

In [191]:
#Passing the features, the target, and test set percentage to the function
def k_Fold_Validation_Classifier(X_data,Y_data,test_percentage):
    #Dividing the data into test set and training set 
    X_train, X_test, y_train, y_test = train_test_split(X_data, Y_data, test_size=test_percentage,random_state=1)
    
    #Shuffling the data to have uniform mix
    X_train,y_train=shuffle(X_train,y_train)
    
    #Initializing a Decision Tree Classifier
    classify=tree.DecisionTreeClassifier()
    
     #Evaluating the Decision Tree Classifier using cross_val_score() function 
    cvs=cross_val_score(classify,X_train,y_train,cv=5)
    
    print("The accuracy on each validation fold of the classifier is: ")
    for scores in cvs:
        print (scores)
    
    #Predicting the value using cross fold validation and finally fitting the classifier
    predicted_value=cross_val_predict(classify,X_test,y_test,cv=5)
    
    #Fitting the classifier using training set
    classify.fit(X_train,y_train)
    
    #Predicting the value using test set in the classifier
    y_pred=classify.predict(X_test)
    
    #The Confusin matrix
    cm=confusion_matrix(y_test,y_pred)
    print("Confusion Matrix:")
    print(cm)
    
    #The Precision Score
    
    print("Precision score %.2f"%precision_score(y_test,y_pred))
    print("Recall score %.2f"%recall_score(y_test,y_pred))
    print("F1 score %.2f"%f1_score(y_test,y_pred))

Training Set: 85% Test Set: 15%

In [192]:
k_Fold_Validation_Classifier(x_data,y_data,0.15)

The accuracy on each validation fold of the classifier is: 
0.9664268585131894
0.9702495201535508
0.9683301343570058
0.9692898272552783
0.9673547767642823
Confusion Matrix:
[[1466   42]
 [  36  295]]
Precision score 0.88
Recall score 0.89
F1 score 0.88


Training Set: 75% Test Set: 25%

In [193]:
k_Fold_Validation_Classifier(x_data,y_data,0.25)

The accuracy on each validation fold of the classifier is: 
0.9717391304347827
0.9717237629146275
0.9679173463839043
0.9651795429815017
0.9662676822633297
Confusion Matrix:
[[2449   62]
 [  50  504]]
Precision score 0.89
Recall score 0.91
F1 score 0.90


Training Set: 65% Test Set: 35%

In [194]:
k_Fold_Validation_Classifier(x_data,y_data,0.35)

The accuracy on each validation fold of the classifier is: 
0.9648902821316614
0.9636135508155583
0.9617074701820465
0.9686126804770873
0.967984934086629
Confusion Matrix:
[[3454   69]
 [  71  697]]
Precision score 0.91
Recall score 0.91
F1 score 0.91
